Repository SOPT-all/35-APPJAM-iOS-ACON, pull requests merged in 2025-01, with the labels that each got.

#2 [SETTING] 프로젝트 초기 세팅 (#1)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ACON-iOS/ACON-iOS.xcodeproj/project.xcworkspace/xcuserdata/sumin.xcuserdatad/UserInterfaceState.xcuserstate
  ACON-iOS/ACON-iOS.xcodeproj/xcuserdata/sumin.xcuserdatad/xcschemes/xcschememanagement.plist
  ACON-iOS/ACON-iOS/AppDelegate.swift
  ACON-iOS/ACON-iOS/Assets.xcassets/AccentColor.colorset/Contents.json
  ACON-iOS/ACON-iOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  ACON-iOS/ACON-iOS/Assets.xcassets/Contents.json
  ACON-iOS/ACON-iOS/Base.lproj/LaunchScreen.storyboard
  ACON-iOS/ACON-iOS/Info.plist
  ACON-iOS/ACON-iOS/SceneDelegate.swift
  ACON-iOS/ACON-iOS/ViewController.swift
Labels: ⚙️ setting, 🍓 수민

#8 [FEAT] 탭바 구현
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Application/SceneDelegate.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Colors/gla_b_30.colorset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/TabBar/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/TabBar/ic_mypage_gla_24.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/TabBar/ic_mypage_gla_24.imageset/ic_mypage_gla_24.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/TabBar/ic_mypage_w_24.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/TabBar/ic_mypage_w_24.imageset/ic_mypage_w_24.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/TabBar/ic_spot_gla_24.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/TabBar/ic_spot_gla_24.imageset/ic_spot_gla_24.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/TabBar/ic_spot_w_24.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/TabBar/ic_spot_w_24.imageset/ic_spot_w_24.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/TabBar/ic_upload_gla_24.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/TabBar/ic_upload_gla_24.imageset/ic_upload_gla_24.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/TabBar/ic_upload_w_24.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/TabBar/ic_upload_w_24.imageset/ic_upload_w_24.svg
  ACON-iOS/ACON-iOS/Presentation/Place/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ProfileViewController.swift
  ACON-iOS/ACON-iOS/Presentation/TabBar/ACTabBarController.swift
  ACON-iOS/ACON-iOS/Presentation/TabBar/Type/ACTabBarItemType.swift
Labels: 🌀 feature, 🥑 유림

#7 [FEAT] 소셜로그인 로직 구현 (#5)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS.xcodeproj/xcshareddata/xcschemes/ACON-iOS.xcscheme
  ACON-iOS/ACON-iOS/Application/SceneDelegate.swift
  ACON-iOS/ACON-iOS/Global/Extensions/UILabel+.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Colors/acBlack.colorset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Colors/acWhite.colorset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Login/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Login/appleLogo.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Login/appleLogo.imageset/ic_apple.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Login/googleLogo.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Login/googleLogo.imageset/ic_google.svg
  ACON-iOS/ACON-iOS/Presentation/Base/BaseNavViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Login/View/LoginView.swift
  ACON-iOS/ACON-iOS/Presentation/Login/View/LoginViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Login/ViewModel/LoginViewModel.swift
Labels: 🌀 feature, 🍓 수민

#10 [FEAT] ACLocationManger 구현 (#9)
  ACON-iOS/.DS_Store
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Extensions/UIViewController+.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Settings/Info.plist
  ACON-iOS/ACON-iOS/Global/Utils/ACLocationManager.swift
  ACON-iOS/ACON-iOS/Global/Utils/MultitaskDelegate.swift
Labels: 🌀 feature, 🍓 수민

#13 [FEAT] ACSheetDetent 설정 (#12)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Extensions/UIViewController+.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Utils/SheetUtils.swift
Labels: 🌀 feature, 🍓 수민

#20 [Chore] .gitignore 수정 (#19)
  .gitignore
  ACON-iOS/.DS_Store
Labels: 🍋‍🟩 chore, 😎 재현

#22 [FEAT] 필터 모달 - 태그 버튼, 스택뷰 커스텀(#16)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Application/SceneDelegate.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Colors/sub_org35.colorset/Contents.json
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Model/SpotListFilterModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Type/FilterTagButtonStackLineType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Type/FilterTagButtonType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Type/SpotType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/Component/FilterTagButton.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/Component/SpotFilterTagButtonStackView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/ViewModel/SpotListFilterViewModel.swift
Labels: 🌀 feature, 🥑 유림

#31 [FEAT] ScreenUtils 보완 - 비율 프로퍼티 생성 (#30)
  ACON-iOS/ACON-iOS/Application/SceneDelegate.swift
  ACON-iOS/ACON-iOS/Global/Utils/ScreenUtils.swift
Labels: 🌀 feature, 🥑 유림

#36 [HOTFIX] 동네인증 프로세스 UI 재머지 (#35)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Extensions/UIButton+.swift
  ACON-iOS/ACON-iOS/Global/Extensions/UIViewController+.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Colors/dim_b_60.colorset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/LocalVerification/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/LocalVerification/icRadio.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/LocalVerification/icRadio.imageset/ic_radio_20.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/LocalVerification/icRadioSelected.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/LocalVerification/icRadioSelected.imageset/ic_radio_pressed_20.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/LocalVerification/localAcorn.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/LocalVerification/localAcorn.imageset/ic_local acon.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/LocalVerification/plainAcorn.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/LocalVerification/plainAcorn.imageset/ic_normal acon.svg
  ACON-iOS/ACON-iOS/Global/Settings/Config/Config.swift
  ACON-iOS/ACON-iOS/Global/Settings/Info.plist
  ACON-iOS/ACON-iOS/Global/Utils/SheetUtils.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseView.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalMapView.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalMapViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationFinishedView.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationFinishedViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationView.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Login/View/LoginViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchViewController.swift
Labels: 🆘 hotfix, 🍓 수민

#32 [FEAT] 장소 필터링 모달 (슬라이더 제외) (#29)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Model/SpotListFilterModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Type/SpotType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/Component/CustomSegmentedControl.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/Component/FilterTagButton.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/Component/PriorityLowEmptyView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/Component/SpotFilterTagButtonStackView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/Component/SpotFilterTagStackView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
Labels: 🌀 feature, 🥑 유림

#28 [FEAT] 장소 추천 컬렉션뷰 - 헤더, dim, footerFeature (#23)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Dim/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Dim/dim_gra_2.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Dim/dim_gra_2.imageset/img_dim_1.svg
  ACON-iOS/ACON-iOS/Presentation/SpotList/Model/SpotModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/Type/SpotListItemSizeType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListCollectionViewHeader.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
Labels: 🌀 feature, 🥑 유림

#38 [FEAT] ACToastController 구현 (#37)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/UIComponents/ACToastController.swift
Labels: 🌀 feature, 🍓 수민

#44 [FEAT] ACDebouncer 구현 (#43)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/UIComponents/ACDebouncer.swift
Labels: 🌀 feature, 🍓 수민

#41 [FEAT] 장소 상세 UI 구현 (#27)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Extensions/Int+.swift
  ACON-iOS/ACON-iOS/Global/Extensions/UILabel+.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotDetail/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotDetail/ic_local.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotDetail/ic_local.imageset/ic_local.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotDetail/ic_no store.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotDetail/ic_no store.imageset/ic_no store image_80.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotDetail/ic_visitor.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotDetail/ic_visitor.imageset/ic_visitor.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotDetail/img_store detail_menulist.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotDetail/img_store detail_menulist.imageset/img_store detail_menulist.svg
  ACON-iOS/ACON-iOS/Global/Settings/Info.plist
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/Model/SpotDetailModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/Cell/MenuCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/Component/StickyHeaderView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/ViewModel/SpotDetailViewModel.swift
Labels: 🌀 feature, 🍓 수민

#42 [FEAT] implement Custom Alert (#25)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/CustomAlert/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/CustomAlert/dotoriX.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/CustomAlert/dotoriX.imageset/dotoriX.svg
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/AlertHandler.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/Type/AlertType.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/View/CustomAlertImageView.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/View/CustomAlertImageViewController.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/View/CustomAlertView.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/View/CustomAlertViewController.swift
Labels: 🌀 feature, 😎 재현

#47 [FEAT] ProfileView (#46)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Application/SceneDelegate.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/construction.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/construction.imageset/construction.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/construction.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/construction.imageset/construction.svg
  ACON-iOS/ACON-iOS/Presentation/Profile/ProfileViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift
Labels: 🌀 feature, 😎 재현

#48 [FEAT] 커스텀 슬라이더 구현 (#33)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Colors/main_org50.colorset/Contents.json
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Type/SpotType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/Component/CustomSlider.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
Labels: 🌀 feature, 🥑 유림

#50 [FEAT] 커스텀 글라스모피즘 구현 (#40)
  ACON-iOS/ACON-iOS/Global/Utils/SheetUtils.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchViewController.swift
Labels: 🌀 feature, 🍓 수민

#53 [FEAT] Implement up button (#51)
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotDetail/upVector.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotDetail/upVector.imageset/upVector.svg
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift
Labels: 🌀 feature, 😎 재현

#55 [FEAT] 장소 조건 설정 - 플로팅버튼 구현, 세그먼트 이동 시 조건 초기화 (#49)
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotFilter/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotFilter/ic_reset.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotFilter/ic_reset.imageset/ic_reset.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotList/ic_filter_b_24.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotList/ic_filter_b_24.imageset/ic_filter_b_24.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotList/ic_filter_w_24.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotList/ic_filter_w_24.imageset/ic_filter_w_24.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotList/ic_my_g_location_24.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotList/ic_my_g_location_24.imageset/ic_my_g_location_24.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotList/ic_my_location_w_24.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/SpotList/ic_my_location_w_24.imageset/ic_my_location_w_24.svg
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/Component/CustomSlider.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/Component/SpotFilterTagStackView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
Labels: 🌀 feature, 🥑 유림

#58 [FEAT] add icon&label to LoginView (#57)
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Login/AconImage.imageset/AconImage.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Login/AconImage.imageset/Contents.json
  ACON-iOS/ACON-iOS/Presentation/Login/View/LoginView.swift
Labels: 🌀 feature, 😎 재현

#61 [SETTING] 네트워크 세팅 (#52)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Application/SceneDelegate.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Utils/Enums/HeaderType.swift
  ACON-iOS/ACON-iOS/Network/Base/ACPlugin.swift
  ACON-iOS/ACON-iOS/Network/Base/ACService.swift
  ACON-iOS/ACON-iOS/Network/Base/BaseService.swift
  ACON-iOS/ACON-iOS/Network/Base/EmptyResponse.swift
  ACON-iOS/ACON-iOS/Network/Base/ErrorResponse.swift
  ACON-iOS/ACON-iOS/Network/Base/NetworkResult.swift
  ACON-iOS/ACON-iOS/Network/Base/TargetType+.swift
  ACON-iOS/ACON-iOS/Network/DummyService.swift
  ACON-iOS/ACON-iOS/Network/Test/DTO/TestResponse.swift
  ACON-iOS/ACON-iOS/Network/Test/TestService.swift
  ACON-iOS/ACON-iOS/Network/Test/TestTargetType.swift
Labels: ⚙️ setting, 🍓 수민

#63 [FEAT] ACWebVC 구현 (#59)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/ACWebViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Login/View/LoginView.swift
  ACON-iOS/ACON-iOS/Presentation/Login/View/LoginViewController.swift
Labels: 🌀 feature, 🍓 수민

#60 [FEAT] Custom Glassmorphism 구현 및 적용 (#56)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/UIComponents/GlassmorphismView.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseNavViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseView.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Component/FloatingButton.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchView.swift
Labels: 🌀 feature, 🥑 유림

#69 [FEAT] 업로드 뷰 뷰모델 구현 및 디자인 변경사항 적용 (#39)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Application/SceneDelegate.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Upload/img_upload_finish.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Upload/img_upload_finish.imageset/img_upload_finish.svg
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop1Acorn.json
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop2Acorn.json
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop3Acorn.json
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop4Acorn.json
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop5Acorn.json
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/finishedUpload.json
  ACON-iOS/ACON-iOS/Global/UIComponents/ACToastController.swift
  ACON-iOS/ACON-iOS/Global/Utils/ACLocationManager.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationFinishedViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/Model/UploadModel.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/Cell/SearchKeywordCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/DropAcornView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/DropAcornViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/ReviewFinishedView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/ReviewFinishedViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotUploadView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotUploadViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/ViewModel/SpotReviewViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/ViewModel/SpotSearchViewModel.swift
Labels: 🌀 feature, 🍓 수민

#66 [CHORE] change design & add alert (#54)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/FavoriteSpotRankCollectionView.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/OnboardingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Type/DislikeCollectionViewType.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Type/FavoriteCuisineType.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Type/FavoriteSpotRankType.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Type/FavoriteSpotStyle.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Type/FavoriteSpotType.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Type/OnboardingType.swift
Labels: 🍋‍🟩 chore, 😎 재현

#73 [CHORE] 업로드 뷰 디자인 변경사항 반영 (#72)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop1Acorn.json
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop2Acorn.json
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop3Acorn.json
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop4Acorn.json
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop5Acorn.json
  ACON-iOS/ACON-iOS/Global/UIComponents/GlassmorphismView.swift
Labels: 🍋‍🟩 chore, 🍓 수민

#76 [HOTFIX] 업로드 뷰 튕기는 오류 해결 (#74)
  ACON-iOS/ACON-iOS/Presentation/TabBar/ACTabBarController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/DropAcornViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/ReviewFinishedViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotUploadViewController.swift
Labels: 🆘 hotfix, 🍓 수민

#81 [FEAT] 일치하는 맛집이 없어요 뷰 구현 (#80)
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListView.swift
Labels: 🌀 feature, 🥑 유림

#79 [FEAT] 탭바 글라스모피즘 적용 (#78)
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListView.swift
  ACON-iOS/ACON-iOS/Presentation/TabBar/ACTabBarController.swift
Labels: 🌀 feature, 🥑 유림

#83 [FEAT] 추천 장소 리스트 Refresh control 커스텀 (#82)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/loadingWhite.json
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Component/CustomRefreshControl.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
Labels: 🌀 feature, 🥑 유림

#89 [FEAT] 장소 상세 네트워크 연결 (#85)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Network/Base/ACService.swift
  ACON-iOS/ACON-iOS/Network/SpotDetail/DTO/GetSpotDetailResponse.swift
  ACON-iOS/ACON-iOS/Network/SpotDetail/DTO/GetSpotMenuResponse.swift
  ACON-iOS/ACON-iOS/Network/SpotDetail/DTO/PostGuidedSpotRequest.swift
  ACON-iOS/ACON-iOS/Network/SpotDetail/SpotDetailService.swift
  ACON-iOS/ACON-iOS/Network/SpotDetail/SpotDetailTargetType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/Model/SpotDetailModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/Cell/MenuCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/ViewModel/SpotDetailViewModel.swift
Labels: ⚪️ network, 🍓 수민

#90 [FIX] 장소 리스트 2번째 셀이 사라지는 문제 해결 (#86)
  ACON-iOS/ACON-iOS/Presentation/SpotList/Type/SpotListItemSizeType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
Labels: ❤️‍🩹 bug, 🥑 유림

#68 [FEAT] 스플래시 UI 구현 (#64)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Application/SceneDelegate.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Login/AconImage.imageset/AconImage.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Login/AconImage.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Login/aconLogo.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Login/aconLogo.imageset/acon_logo.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Onboarding/checkLottie.dataset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/construction.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/construction.imageset/construction.svg
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/checkLottie.json
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/lodingLottie.json
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/splashLottie.json
  ACON-iOS/ACON-iOS/Presentation/Login/View/LoginView.swift
  ACON-iOS/ACON-iOS/Presentation/Splash/View/SplashView.swift
  ACON-iOS/ACON-iOS/Presentation/Splash/View/SplashViewController.swift
Labels: 🌀 feature, 🍓 수민

#97 [FEAT] 로그인 모달 뷰 구현 (#96)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Presentation/LoginModal/View/LoginModalView.swift
  ACON-iOS/ACON-iOS/Presentation/LoginModal/View/LoginModalViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
Labels: 🌀 feature, 🥑 유림

#84 [FEAT] 동네인증 네트워크 연결 (#70)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Network/Base/ACService.swift
  ACON-iOS/ACON-iOS/Network/LocalVerification/DTO/PostLocalAreaRequest.swift
  ACON-iOS/ACON-iOS/Network/LocalVerification/DTO/PostLocalAreaResponse.swift
  ACON-iOS/ACON-iOS/Network/LocalVerification/LocalVerificationService.swift
  ACON-iOS/ACON-iOS/Network/LocalVerification/LocalVerificationTargetType.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalMapViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationFinishedViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/ViewModel/LocalVerificationViewModel.swift
Labels: ⚪️ network, 🍓 수민

#95 [CHORE] 장소 상세 UI 변경사항 반영 (#91)
  ACON-iOS/ACON-iOS/Global/Extensions/UIView+.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/Cell/MenuCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/ViewModel/SpotDetailViewModel.swift
Labels: 🍋‍🟩 chore, 🍓 수민

#99 [FEAT] 구글 로그인 네트워크 연결 (#88)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Utils/Enums/HeaderType.swift
  ACON-iOS/ACON-iOS/Global/Utils/Enums/SocialType.swift
  ACON-iOS/ACON-iOS/Network/Auth/AuthService.swift
  ACON-iOS/ACON-iOS/Network/Auth/AuthTargetType.swift
  ACON-iOS/ACON-iOS/Network/Auth/DTO/PostLoginRequest.swift
  ACON-iOS/ACON-iOS/Network/Auth/DTO/PostLoginResponse.swift
  ACON-iOS/ACON-iOS/Network/Base/ACService.swift
  ACON-iOS/ACON-iOS/Presentation/Login/View/LoginViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Login/ViewModel/LoginViewModel.swift
Labels: ⚪️ network, 🍓 수민

#98 [FEAT] 업로드 네트워크 연결 (#71)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/AlertHandler.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/Type/AlertType.swift
  ACON-iOS/ACON-iOS/Global/Utils/Enums/SpotCategoryType.swift
  ACON-iOS/ACON-iOS/Network/Base/ACService.swift
  ACON-iOS/ACON-iOS/Network/SpotDetail/DTO/GetSpotDetailResponse.swift
  ACON-iOS/ACON-iOS/Network/Upload/DTO/GetAcornCountResponse.swift
  ACON-iOS/ACON-iOS/Network/Upload/DTO/GetReiviewVerificationRequest.swift
  ACON-iOS/ACON-iOS/Network/Upload/DTO/GetReviewVerificationResponse.swift
  ACON-iOS/ACON-iOS/Network/Upload/DTO/GetSearchKeywordRequest.swift
  ACON-iOS/ACON-iOS/Network/Upload/DTO/GetSearchKeywordResponse.swift
  ACON-iOS/ACON-iOS/Network/Upload/DTO/GetSearchSuggestionRequest.swift
  ACON-iOS/ACON-iOS/Network/Upload/DTO/GetSearchSuggestionResponse.swift
  ACON-iOS/ACON-iOS/Network/Upload/DTO/PostReviewRequest.swift
  ACON-iOS/ACON-iOS/Network/Upload/UploadService.swift
  ACON-iOS/ACON-iOS/Network/Upload/UploadTargetType.swift
  ACON-iOS/ACON-iOS/Presentation/LoginModal/View/LoginModalViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/ViewModel/SpotDetailViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/Model/UploadModel.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/DropAcornView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/DropAcornViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotUploadViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/ViewModel/SpotReviewViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/ViewModel/SpotSearchViewModel.swift
Labels: ⚪️ network, 🍓 수민

#75 [FEAT] Onboarding Networking (#67)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Network/Base/ACService.swift
  ACON-iOS/ACON-iOS/Network/Onboarding/DTO/OnboardingRequest.swift
  ACON-iOS/ACON-iOS/Network/Onboarding/OnboardingService.swift
  ACON-iOS/ACON-iOS/Network/Onboarding/OnboardingTargetType.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/Model/OnboardingMapping.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/AnalyzingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Cell/BigBoxViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Cell/LongBoxViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Cell/SmallBoxViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/FavoriteSpotRankCollectionView.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/OnboardingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Type/DislikeCollectionViewType.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/ViewModel/OnboardingViewModel.swift
Labels: 🌀 feature, ⚪️ network, 😎 재현

#103 [CHORE] app icon add (#102)
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/logo_final.png
Labels: 🍋‍🟩 chore, 😎 재현

#104 [FEAT] 위치 기반 장소 추천 네트워크 연결 (#87)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Network/Base/ACService.swift
  ACON-iOS/ACON-iOS/Network/SpotList/DTO/PostSpotListRequest.swift
  ACON-iOS/ACON-iOS/Network/SpotList/DTO/PostSpotListResponse.swift
  ACON-iOS/ACON-iOS/Network/SpotList/SpotListService.swift
  ACON-iOS/ACON-iOS/Network/SpotList/SpotListTargetType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/Model/SpotModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/ViewModel/SpotListViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Model/SpotListFilterModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Type/SpotType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
Labels: 🌀 feature, 🥑 유림

#108 [CHORE] Onboarding design fix (#105)
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Cell/BigBoxViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Cell/LongBoxViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Cell/SmallBoxViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/DislikeCollectionView.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/FavoriteCuisineCollectionView.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/OnboardingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/ViewModel/OnboardingViewModel.swift
Labels: 🍋‍🟩 chore, 😎 재현

#113 [FIX] Onboarding QA (#109)
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Cell/SmallBoxViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/FavoriteSpotRankCollectionView.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/FavoriteSpotStyleCollectionView.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/FavoriteSpotTypeCollectionView.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/OnboardingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Type/FavoriteSpotStyle.swift
Labels: 🍋‍🟩 chore, 😎 재현

#116 [FEAT] 필터뷰 슬라이더 POST 바인딩 (#115)
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/ViewModel/SpotListViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Type/SpotType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/Component/CustomSlider.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
Labels: 🌀 feature, ⚪️ network, 🥑 유림

#117 [FIX] 1차 QA 반영 (#110)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/splashLottie.json
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/AlertHandler.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/GlassmorphismView.swift
  ACON-iOS/ACON-iOS/Network/Upload/UploadTargetType.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseNavViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalMapViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationFinishedView.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationFinishedViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationView.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/Type/SpotListItemSizeType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/Component/CustomSlider.swift
  ACON-iOS/ACON-iOS/Presentation/TabBar/ACTabBarController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/DropAcornViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/ReviewFinishedViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotUploadView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotUploadViewController.swift
Labels: ❤️‍🩹 bug, 🍓 수민

#118 [FEAT] 자동로그인 구현 및 게스트 진입 프로세스 구현 (#100)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Extensions/UIViewController+.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Service/AuthManager.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/LoginModal/View/LoginModalView.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/LoginModal/View/LoginModalViewController.swift
  ACON-iOS/ACON-iOS/Network/SpotList/DTO/PostSpotListResponse.swift
  ACON-iOS/ACON-iOS/Presentation/Login/View/LoginViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Splash/View/SplashViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/Model/SpotModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/Component/CustomSlider.swift
  ACON-iOS/ACON-iOS/Presentation/TabBar/ACTabBarController.swift
Labels: 🌀 feature, 🍓 수민

#120 [FEAT] 스켈레톤 뷰 구현 (#107)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Component/SkeletonView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
Labels: 🌀 feature, 🥑 유림

#123 [FEAT] EmptyView in upload, search view (#119)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SearchEmptyView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchViewController.swift
Labels: 🌀 feature, 😎 재현

#126 [CHORE] 에셋 수정 dropAcorn, loadingWhite (#125)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop1Acorn.json
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop2Acorn.json
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop3Acorn.json
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop4Acorn.json
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop5Acorn.json
Labels: 🍋‍🟩 chore, 🥑 유림

#128 [CHORE] v1.0 테플 배포 준비 (#121)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS.xcodeproj/xcshareddata/xcschemes/ACON-iOS.xcscheme
  ACON-iOS/ACON-iOS/ACON-iOSRelease.entitlements
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/appIcon.png
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/logo_final.png
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotUploadViewController.swift
Labels: 🍋‍🟩 chore, 🍓 수민

#131 [FIX] 리프레시 컨트롤 안 보이는 문제 해결, 장소리스트 포스트 로직 변경, 탭바 문제 해결 (#127)
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Component/CustomRefreshControl.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/ViewModel/SpotListViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
  ACON-iOS/ACON-iOS/Presentation/TabBar/ACTabBarController.swift
Labels: 🆘 hotfix, 🥑 유림

#133 [CHORE] onboarding second time QA (#132)
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Onboarding/1.imageset/1.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Onboarding/2.imageset/2.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Onboarding/3.imageset/3.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Onboarding/4.imageset/4.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Onboarding/check.imageset/check.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Onboarding/specialPlace.imageset/specialPlace.png
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Cell/BigBoxViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Cell/LongBoxViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Cell/SmallBoxViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/FavoriteSpotTypeCollectionView.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/OnboardingViewController.swift
Labels: 🍋‍🟩 chore, 😎 재현

#135 [FIX] 2차 QA 반영 (#129)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/appIcon.png
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/appstore.png
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/LocalVerification/ic_mark_48.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/LocalVerification/ic_mark_48.imageset/ic_mark_48.svg
  ACON-iOS/ACON-iOS/Global/Utils/ACLocationManager.swift
  ACON-iOS/ACON-iOS/Network/SpotList/DTO/PostSpotListResponse.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalMapView.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalMapViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Login/View/LoginView.swift
  ACON-iOS/ACON-iOS/Presentation/Splash/View/SplashView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/DropAcornView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/ReviewFinishedView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/ReviewFinishedViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotUploadViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/ViewModel/SpotReviewViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/ViewModel/SpotSearchViewModel.swift
Labels: ❤️‍🩹 bug, 🍓 수민

#139 [FEAT] 법정동 조회 API 연결 (#130)
  ACON-iOS/ACON-iOS/Network/SpotList/SpotListService.swift
  ACON-iOS/ACON-iOS/Network/SpotList/SpotListTargetType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/ViewModel/SpotListViewModel.swift
Labels: 🌀 feature, 🍓 수민

#143 [Chore] clean code (#142)
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/OnboardingViewController.swift
Labels: 🍋‍🟩 chore, 😎 재현

#144 [DOCS] 리드미 작성 (#137)
  README.md
Labels: 📘 docs, 🍓 수민

#141 [HOTFIX] 필터 초기화, 데이터 없을 때 노아콘뷰 보이게 수정, 취향일치율 hidden, 데이터 변경 없을 때 스켈레톤 hidden 풀기, DetailVC에 id 넘겨주기 (#138)
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/ViewModel/SpotListViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
Labels: 🆘 hotfix, 🥑 유림

#146 [HOTFIX] 앱 첫 진입 후 POST시 거리, 가격이 잘못 보내지는 것 수정 (#145)
  ACON-iOS/ACON-iOS/Presentation/SpotList/ViewModel/SpotListViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Type/SpotType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
  README.md
Labels: 🆘 hotfix, 🥑 유림
